site_name: Space-Time Matrix Tools Documentation
repo_url: https://github.com/tudelftgeodesy/stmtools/
repo_name: STM Tools

nav:
  - Getting started: 
    - About STM Tools: index.md
    - Installation: setup.md
  - Usage: 
    - Initiate an STM: stm_init.md
    - Operations on STM: operations.md
    - Ordering an STM: order.md
  - Example Notebooks:
    - Example Operations: notebooks/demo_operations_stm.ipynb
    - Example Ordering: notebooks/demo_order_stm.ipynb
  - Contributing guide: CONTRIBUTING.md
  - Change Log: CHANGELOG.md


theme:
  name: material
  custom_dir: docs/notebooks/download_button
  logo: img/stmtools_logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: grey
      accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  
plugins:
- mkdocs-jupyter:
      include_source: True
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: no
          merge_init_into_class: yes
          show_submodules: no

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  generator: false